version: '3.7'
services:
  backend-api:
    container_name: backend-api
    depends_on:
      - database
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=database 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres 

  database:
    container_name: database
    image: postgres:11.1
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    
  frontend:
  # frontend container, we are using react-native with expo
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/code
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      # Set the ip as being the same as the host machine
      - REACT_NATIVE_PACKAGER_HOSTNAME="localhost"